In [1]:
import numpy as np

# rand -->

In [2]:
x = np.random.rand(4) # create an array of 4 random elements between 0 & 1 
print(x)

[0.27771238 0.72938073 0.59057178 0.90263838]


In [3]:
x = np.random.rand(2, 4) # create an 2D array of random elements between 0 & 1 with 2 rows & 4 column
print(x)

[[0.5617857  0.11293154 0.56188306 0.14587557]
 [0.33838576 0.05168502 0.95622472 0.52941004]]


# randn -->

In [4]:
x = np.random.randn(5) # create an array of 5 size with random elements close to 0 including -ve numbers
print(x)

[-0.67176903  3.03922818  0.19562938  0.61864455 -0.35051356]


# ranf -->

In [5]:
x = np.random.ranf(4) # create an array of float of 4 size with random elements between 0.0 & 1.0(excluding 1.0)
print(x)

[0.23035881 0.8760513  0.98474057 0.51296935]


# randint -->

In [6]:
x = np.random.randint(100, 200, 10) # create an array of 10 size with random elements between 100 & 200
print(x)

[105 107 124 107 151 173 166 142 154 101]
