In [1]:
import numpy as np

In [10]:
x1 = np.array([1,2,3,4])
x2 = np.array([1,2,3])

print(x1 + x2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [8]:
x1 = np.array([1,2,3,])
print("Shape of x1: ",x1.shape)
print(x1)

print("---------------------")

x2 = np.array([[1], [2], [3]])
print("Shape of x2: ",x2.shape)
print(x2)

print("-----------------------")

print(x1 + x2)

Shape of x1:  (3,)
[1 2 3]
---------------------
Shape of x2:  (3, 1)
[[1]
 [2]
 [3]]
-----------------------
[[2 3 4]
 [3 4 5]
 [4 5 6]]
