In [1]:
import numpy as np

# Creating array -->

In [2]:
a = np.array([1,2,3,4,5,6]) # creating array using list
print(a)

[1 2 3 4 5 6]


In [3]:
a = [1,2,3,4,5,6]
x = np.array(a) #creating array using list variable
print(x)

[1 2 3 4 5 6]


In [9]:
l = []

# Creating array using user input
for i in range(1, 5):
    value = int(input("Enter your number: "))
    l.append(value)

print(np.array(l))

Enter your number:  5
Enter your number:  5
Enter your number:  5
Enter your number:  5


[5 5 5 5]


# Different dimensions array -->

In [19]:
x = np.array([10,20,30,40,50]) # 1d array
print(x)

print(x.ndim) # determine the dimension of array

[10 20 30 40 50]
1


In [14]:
x = np.array([[10,20,30,40], [50,60,70,80]]) # 2d array
print(x)

print(x.ndim) # determine the dimension of array

[[10 20 30 40]
 [50 60 70 80]]
2


In [15]:
x = np.array([[[10,20,30,40], [50,60,70,80]]]) # 3d array
print(x)

print(x.ndim) # determine the dimension of array

[[[10 20 30 40]
  [50 60 70 80]]]
3


In [18]:
x = np.array([10,20,30,40], ndmin=10) # creating 10d array
print(x)

print(x.ndim) # determine the dimension of array

[[[[[[[[[[10 20 30 40]]]]]]]]]]
10
