In [1]:
import numpy as np

# Search(where) --> return the index of element

In [2]:
x = np.array([1,2,3,4,2,5,2,5,6,7])

ans = np.where(x == 2) # return index of element
print(ans)

(array([1, 4, 6]),)


In [3]:
x = np.array([1,2,3,4,2,5,2,5,6,7])

ans = np.where((x%2) == 0)
print(ans)

(array([1, 3, 4, 6, 8]),)


# searchsorted --> return the index at which element should insert

In [8]:
x = np.array([1,2,3,4,6,7,8,9])

index = np.searchsorted(x, 5)
print("Insert on index: ",index)

Insert on index:  4


In [9]:
x = np.array([1,2,3,4,6,7,8,9,11,12,13])

index = np.searchsorted(x, [5,10,14])
print("Insert on index: ",index)

Insert on index:  [ 4  8 11]


# sort -->

In [10]:
x = np.array([7,54,21,9,6,1,485,23,7])
print(x)

print(np.sort(x))

[  7  54  21   9   6   1 485  23   7]
[  1   6   7   7   9  21  23  54 485]


In [12]:
x = np.array([[4,2,3], [1,12,5], [22,52,6]])
print(x)
print("-----------------")

print(np.sort(x))

[[ 4  2  3]
 [ 1 12  5]
 [22 52  6]]
-----------------
[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


# Filter Array -->

In [14]:
x = np.array(["a", "s", "d", "f"])

f = [True, False, False, True]

new = x[f]
print(new)

['a' 'f']
