In [3]:
import numpy as np

# shape -->

In [12]:
x = np.array([[1,2,3,4], [1,2,3,4]])

print(x)
print()
print("Shape of x: ",x.shape) # print number of rows and column

[[1 2 3 4]
 [1 2 3 4]]

Shape of x:  (2, 4)


# reshape -->

In [16]:
x = np.array([1,2,3,4,5,6])
print(x)
print(x.ndim)

print()

new = x.reshape(3, 2) # change the dimension of x to 2D with 3 rows & 2 columns
print(new)
print(new.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [31]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
print("Dim of x: ",x.ndim)

print("---------------")

new = x.reshape(2,3,2) # change the dimension of x to 3D with 2 rows, 3 rows & 2 columns
print(new)
print("Dim of new: ",new.ndim)

print("---------------")

old = new.reshape(-1) # change the dimension of new to 1D
print(old)
print("Dim of old: ",old.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dim of x:  1
---------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dim of new:  3
---------------
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dim of old:  1
