In [1]:
import numpy as np

# Data Types -->

In [2]:
x = np.array([1,2,3,5,4,8,6])
print("Data Type: ", x.dtype)

Data Type:  int64


In [5]:
x = np.array([1.5, 3.8, 4.41, 8.3])
print("Data Type: ", x.dtype)

Data Type:  float64


In [6]:
x = np.array(["a", "s", "d", "f"])
print("Data Type: ", x.dtype)

Data Type:  <U1


In [7]:
x = np.array(["a", "s", "d", 5,6,7,2])
print("Data Type: ", x.dtype)

Data Type:  <U21


# Changing data type -->

In [11]:
x = np.array([1,2,3,4], dtype = np.int8) # change to int8
print("Data Type: ", x.dtype)

Data Type:  int8


In [12]:
x = np.array([1,2,3,4], dtype = "f") # change to float
print("Data Type: ", x.dtype)
print(x)

Data Type:  float32
[1. 2. 3. 4.]


In [16]:
x = np.array([1,2,3,4])
new = np.float32(x) # change data type to float using function

print("Data Type of x: ", x.dtype)
print("Data Type of new: ", new.dtype)

print(x)
print(new)

Data Type of x:  int64
Data Type of new:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [17]:
x = np.array([1,2,3,4])
new = x.astype(float)

print(x)
print(new)

[1 2 3 4]
[1. 2. 3. 4.]
