In [1]:
import numpy as np

# Indexing -->

In [3]:
x = np.array([10,20,30,40])

print(x[2])
print(x[-3]) # totalSize - number

30
20


In [6]:
x = np.array([[9,8,7], [4,5,6]])

print(x)
print("Element it index 0,2: ",x[0, 2])

[[9 8 7]
 [4 5 6]]
Element it index 0,2:  7


In [8]:
x = np.array([[[1,2], [6,7]]])

print(x)
print("Element it index 0,1,1: ",x[0, 1, 1])

[[[1 2]
  [6 7]]]
Element it index 0,1,1:  7


# Slicing -->

In [16]:
x = np.array([10,20,30,40,50,60,70])

print(x)

print("20 to 40: ", x[1:4])
print("20 to end: ", x[1:])
print("start to 50: ", x[:5])
print("Every 2nd element ", x[::2])

[10 20 30 40 50 60 70]
20 to 40:  [20 30 40]
20 to end:  [20 30 40 50 60 70]
start to 50:  [10 20 30 40 50]
Every 2nd element  [10 30 50 70]


In [19]:
x = np.array([[1,2,3,4,5], [9,8,7,6,5], [11,12,13,14,15]])

print(x)
print(x[1, 1:4])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
[8 7 6]
