In [1]:
import numpy as np

# Join Array -->

In [8]:
x1 = np.array([1,2,3,4])
x2 = np.array([9,8,7,6])

new = np.concatenate((x1, x2))

print(new)

[1 2 3 4 9 8 7 6]


In [27]:
x1 = np.array([[1,2], [3,4]])
x2 = np.array([[9,8], [7,6]])

print(x1)
print("-------------------")
print(x2)
print("-------------------")


new1 = np.concatenate((x1, x2), axis=0)
new2 = np.concatenate((x1, x2), axis=1)

print("axis=0\n", new1)
print("-------------------")
print("axis=1\n", new2)

[[1 2]
 [3 4]]
-------------------
[[9 8]
 [7 6]]
-------------------
axis=0
 [[1 2]
 [3 4]
 [9 8]
 [7 6]]
-------------------
axis=1
 [[1 2 9 8]
 [3 4 7 6]]


In [28]:
# stack is left

# Split Array -->

In [38]:
x = np.array([1,2,3,4,5,6])
print(x)
print("------------------------")

new = np.array_split(x, 4) # data will be stored in a list
print(new)
print("type of new: ",type(new))

print(new[1])

[1 2 3 4 5 6]
------------------------
[array([1, 2]), array([3, 4]), array([5]), array([6])]
type of new:  <class 'list'>
[3 4]
